site_name: My Docs
site_url: https://mydomain.org
plugins:
  - tags
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - header.autohide
    - announce.dismiss
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
